name: tic_tac_toe
description: Jogo da velha 
version: 1.0.2+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.3+4
  flutter_automation: ^1.3.3
  

  provider: ^4.3.2+1
  google_sign_in: ^4.5.3
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.2+1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/ic_party.png


